export const PRODUCTS_REQUEST = {
	BEGIN: "PRODUCTS_IS_FETCHING",
	SUCCESS: "PRODUCTS_REQUEST_SUCCESS"
};

export const STORES_REQUEST = {
	BEGIN: "STORES_IS_FETCHING",
	SUCCESS: "STORES_REQUEST_SUCCESS"
};